spring:
  datasource:
    url: ${vcap.services.cf-forge-db.credentials.jdbcUrl:}
    username: ${vcap.services.cf-forge-db.credentials.username:}
    password: ${vcap.services.cf-forge-db.credentials.password:}
  data:
    redis:
      host: ${vcap.services.cf-forge-cache.credentials.host:}
      port: ${vcap.services.cf-forge-cache.credentials.port:6379}
      password: ${vcap.services.cf-forge-cache.credentials.password:}
  rabbitmq:
    host: ${vcap.services.cf-forge-mq.credentials.hostname:}
    port: ${vcap.services.cf-forge-mq.credentials.port:5672}
    username: ${vcap.services.cf-forge-mq.credentials.username:}
    password: ${vcap.services.cf-forge-mq.credentials.password:}
    virtual-host: ${vcap.services.cf-forge-mq.credentials.vhost:/}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${vcap.services.cf-forge-sso.credentials.auth_domain:${SSO_ISSUER_URI:}}

cf:
  forge:
    sso:
      client-id: ${vcap.services.cf-forge-sso.credentials.client_id:${SSO_CLIENT_ID:}}
      client-secret: ${vcap.services.cf-forge-sso.credentials.client_secret:${SSO_CLIENT_SECRET:}}
      issuer-uri: ${vcap.services.cf-forge-sso.credentials.auth_domain:${SSO_ISSUER_URI:}}
