spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
  datasource:
    url: ${vcap.services.cf-forge-db.credentials.jdbcUrl:}
    username: ${vcap.services.cf-forge-db.credentials.username:}
    password: ${vcap.services.cf-forge-db.credentials.password:}
  rabbitmq:
    host: ${vcap.services.cf-forge-mq.credentials.hostname:}
    port: ${vcap.services.cf-forge-mq.credentials.port:5672}
    username: ${vcap.services.cf-forge-mq.credentials.username:}
    password: ${vcap.services.cf-forge-mq.credentials.password:}
  ai:
    vectorstore:
      pgvector:
        dimensions: 768
        distance-type: cosine_distance
        index-type: hnsw
