spring:
  ai:
    openai:
      base-url: ${vcap.services.cf-forge-genai.credentials.api_base}
      api-key: ${vcap.services.cf-forge-genai.credentials.api_key}
      chat:
        options:
          model: ${vcap.services.cf-forge-genai.credentials.model}
  datasource:
    url: ${vcap.services.cf-forge-db.credentials.jdbcUrl:}
    username: ${vcap.services.cf-forge-db.credentials.username:}
    password: ${vcap.services.cf-forge-db.credentials.password:}
  rabbitmq:
    host: ${vcap.services.cf-forge-mq.credentials.hostname:}
    port: ${vcap.services.cf-forge-mq.credentials.port:5672}
    username: ${vcap.services.cf-forge-mq.credentials.username:}
    password: ${vcap.services.cf-forge-mq.credentials.password:}
